In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('Fraud Detection Data.csv')

In [23]:
df.head()

,Unnamed: 0,record_id,country,year,claim_amount_usd,policy_duration_months,previous_claims_count,reporting_delay_days,document_completeness_score,claimant_age,claim_type,seasonality_flag,amount_deviation_zscore,duplicate_claim_flag,fraud_label,fraud_probability,fraud_scheme_type,detection_method,recovery_amount_usd
0,0,1,South Africa,2024,3470.38,107,0,2,0.763,35,property,0,0.287,1,1,0.1163,inflated_claim,ml_model,1749.60
1,1,2,South Africa,2024,512.03,94,4,12,0.543,40,health,1,-1.188,0,0,0.1042,none,none,0.00
2,2,3,South Africa,2024,4450.99,82,2,6,0.625,55,travel,1,0.776,1,0,0.1512,none,none,0.00
3,3,4,South Africa,2024,4869.24,30,5,6,0.797,46,health,0,0.984,0,1,0.2996,collusion,rule_based,2803.31
4,4,5,South Africa,2024,50.00,75,0,27,0.882,40,life,0,-1.419,0,0,0.0802,none,none,0.00

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360000 entries, 0 to 359999
Data columns (total 19 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   360000 non-null  int64
 1   record_id                    360000 non-null  int64
 2   country                      360000 non-null  str
 3   year                         360000 non-null  int64
 4   claim_amount_usd             360000 non-null  float64
 5   policy_duration_months       360000 non-null  int64
 6   previous_claims_count        360000 non-null  int64
 7   reporting_delay_days         360000 non-null  int64
 8   document_completeness_score  360000 non-null  float64
 9   claimant_age                 360000 non-null  int64
 10  claim_type                   360000 non-null  str
 11  seasonality_flag             360000 non-null  int64
 12  amount_deviation_zscore      360000 non-null  float64
 13  duplicate_claim_flag         360000 non-null  int64
 14  fraud_label                  360000 non-null  int64
 15  fraud_probability            360000 non-null  float64
 16  fraud_scheme_type            360000 non-null  str
 17  detection_method             360000 non-null  str
 18  recovery_amount_usd          360000 non-null  float64
dtypes: float64(5), int64(10), str(4)
memory usage: 60.3 MB

In [25]:
columns_to_drop = [
    'fraud_scheme_type', 
    'detection_method', 
    'recovery_amount_usd', 
    'fraud_probability', 
    'record_id',
    'Unnamed: 0'
]
df_cleaned = df.drop(columns=columns_to_drop)

In [26]:
df_cleaned.head()

,country,year,claim_amount_usd,policy_duration_months,previous_claims_count,reporting_delay_days,document_completeness_score,claimant_age,claim_type,seasonality_flag,amount_deviation_zscore,duplicate_claim_flag,fraud_label
0,South Africa,2024,3470.38,107,0,2,0.763,35,property,0,0.287,1,1
1,South Africa,2024,512.03,94,4,12,0.543,40,health,1,-1.188,0,0
2,South Africa,2024,4450.99,82,2,6,0.625,55,travel,1,0.776,1,0
3,South Africa,2024,4869.24,30,5,6,0.797,46,health,0,0.984,0,1
4,South Africa,2024,50.00,75,0,27,0.882,40,life,0,-1.419,0,0

In [27]:
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 360000 entries, 0 to 359999
Data columns (total 13 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   country                      360000 non-null  str
 1   year                         360000 non-null  int64
 2   claim_amount_usd             360000 non-null  float64
 3   policy_duration_months       360000 non-null  int64
 4   previous_claims_count        360000 non-null  int64
 5   reporting_delay_days         360000 non-null  int64
 6   document_completeness_score  360000 non-null  float64
 7   claimant_age                 360000 non-null  int64
 8   claim_type                   360000 non-null  str
 9   seasonality_flag             360000 non-null  int64
 10  amount_deviation_zscore      360000 non-null  float64
 11  duplicate_claim_flag         360000 non-null  int64
 12  fraud_label                  360000 non-null  int64
dtypes: float64(3), int64(8), str(2)
memory usage: 40.4 MB

In [28]:
df_cleaned['fraud_label'].sum()

np.int64(49197)

In [30]:
df_cleaned.to_csv('CleandData.csv',index=False)